{% set version = "0.7.2" %}

package:
  name: obstore
  version: {{ version }}

source:
  url: https://github.com/developmentseed/obstore/archive/refs/tags/py-v{{ version }}.tar.gz
  sha256: f2e6529b7d3e94902e52b3f894bd0bba07ee2505ea7401b115d868d1eefa8c9b

build:
  script:
    - {{ PYTHON }} -m pip install ./obstore -vv
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin >=1.7.0,<2.0                   # [build_platform != target_platform]
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
    - {{ compiler("rust") }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1.4.0,<2.0
    - pip
  run:
    - python
    - typing_extensions >=4.0.0  # [py<313]

test:
  imports:
    - obstore
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/developmentseed/obstore
  summary: Simple, fast integration with Amazon S3, Google Cloud Storage, Azure Storage, and S3-compliant APIs like Cloudflare R2.
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  license_url: https://github.com/developmentseed/obstore/blob/main/LICENSE
  doc_url: https://developmentseed.org/obstore/latest/
  dev_url: https://github.com/developmentseed/obstore

extra:
  recipe-maintainers:
    - kylebarron
